run:
  deadline: 5m

linters:
  fast: false
  enable:
    - asciicheck
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/selectel/go-selvpcclient
          - github.com/gophercloud/gophercloud
          - github.com/google/go-querystring
  goimports:
    local-prefixes: github.com/selectel/go-selvpcclient
  gci:
    local-prefixes: github.com/selectel/go-selvpcclient
